Algoritmo "semnome"

Var
 n1, n2 : inteiro
 nome1 , nome2 : caractere

Inicio
escreval ("olá. informe um nome")
leia (nome1)
escreval ("informe a altura")
leia (n1)
escreval ("informe o segundo nome?")
leia (nome2)
escreval ("informe a segunda altura?")
leia(n2)
escreval
se (n1 >= n2) entao
   escreval ("a maior altura é de ",  nome1)
   escreval ("sua altura é de", n1)
 senao
   escreval ("a maior altura é de ",  nome2)
   escreval ("sua altura é de ", n2)
fimse
Fimalgoritmo